# Generated by Django 4.2.7 on 2023-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.EmailField(max_length=254)),
                ('login_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lname',
            new_name='last_name',
        ),
    ]
