# Generated by Django 4.2.7 on 2023-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login_rename_fname_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
