# Generated by Django 4.2.7 on 2023-11-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_status_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_First_Name', models.CharField(max_length=50)),
                ('Registration_Last_Name', models.CharField(max_length=50)),
                ('Registration_city', models.CharField(max_length=50)),
                ('Registration_email', models.EmailField(max_length=254)),
                ('Registration_number', models.PositiveBigIntegerField()),
                ('Registration_password', models.CharField(max_length=8)),
                ('Registration_confirm_password', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
